// Copyright 2026 The Android Open Source Project
// Copyright 2026 Sovereign Lane Surgeon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

// bundle.go — the bundle as CONTENT-ADDRESSED data, separable from the binary.
//
// The binary always embeds the bundle MANIFEST (assets/aosp15_device.sha256: sha256, size and
// path of all ~7100 files, regenerated by `go generate`); bundleID is the hash of that manifest.
// The bundle CONTENT comes from the first of these that is present and verifies:
//
//	builtin        the default build embeds it (embeddedassets.go)
//	-bundle-dir    a directory (or $SLS_BUNDLE_DIR)
//	cache          $XDG_CACHE_HOME/sovereign-lane-surgeon/bundle/<id>/ (or ~/.cache/…)
//	-bundle-url    a .tar.gz fetched into the cache (or $SLS_BUNDLE_URL)
//
// Every non-builtin source is verified file by file against the manifest before it is used
// (a stamp file records a verified directory so the hash pass runs once); a directory or
// archive that does not match the manifest this binary was built with is refused, whatever
// its name. `bundle export` writes the archive + manifest from a builtin binary for publishing,
// so `go build -tags nobundle` (~5MB) plus one published archive per bundle id replaces the
// ~510MB binary for distribution and CI.

// ONE generator emits every manifest below (content, exec bits, symlinks, empty dirs), because
// each loss embed inflicts was found the same expensive way — a build failing far from the cause
// — and fixed one at a time, so a new KIND of loss had nothing regenerating it. `bundle audit`
// proves the set complete against a real source tree.
//
//go:generate go run ./cmd/bundlemanifest
//go:embed assets/aosp15_device.sha256
var embeddedBundleManifest string

// embed.FS carries file contents only: every embedded file stats as 0444, so the executable bit
// AOSP's scripts rely on (kati runs device/google/tangorpro/uwb/country_conf_gen.sh via $(shell)
// and errors "Permission denied" at 0644) has to travel separately. materializeEmbedded writes
// listed paths as 0755, and exportBundle records them as 0755 in the archive.
//
//go:embed assets/aosp15_device.exec
var embeddedExecManifest string

// embeddedExecutables is the exec manifest as a set of bundle-relative, forward-slashed paths.
var embeddedExecutables = func() map[string]bool {
	set := map[string]bool{}
	for _, line := range strings.Split(embeddedExecManifest, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		set[line] = true
	}
	return set
}()

// go:embed also drops SYMLINKS entirely (embed.FS cannot represent one; the walk does not even
// yield them). AOSP's trees use them as compatibility headers — zuma's
// include/displaycolor/displaycolor_gs101.h -> ../gs101/displaycolor/displaycolor_gs101.h is how
// its own displaycolor_zuma.h resolves that include against the module's include_dirs. Losing it
// costs nothing until something compiles libacryl, then fails with "file not found" 46 minutes
// into a build (husky, 2026-09-03, run 083328Z). materializeEmbedded recreates each link
// (copying the target's bytes when the filesystem refuses a symlink).
//
//go:embed assets/aosp15_device.symlinks
var embeddedSymlinkManifest string

type bundleSymlink struct{ Path, Target string }

// parseSymlinkManifest reads "<link path>\t<link target>" lines (comments and blanks skipped).
func parseSymlinkManifest(text string) []bundleSymlink {
	var out []bundleSymlink
	for _, line := range strings.Split(text, "\n") {
		if strings.TrimSpace(line) == "" || strings.HasPrefix(line, "#") {
			continue
		}
		f := strings.SplitN(line, "\t", 2)
		if len(f) != 2 || f[0] == "" || f[1] == "" {
			continue
		}
		out = append(out, bundleSymlink{Path: f[0], Target: f[1]})
	}
	return out
}

var bundleSymlinks = parseSymlinkManifest(embeddedSymlinkManifest)

// A directory holding no files at any depth is the third thing embed cannot carry: embed.FS is a
// set of files, so a directory that exists in order to be empty simply does not appear. The
// bundle has none today (measured 2026-09-03, across both source tags) — this manifest exists so
// that a future release which adds one does not lose it silently, and so `bundle audit` has
// something to compare against.
//
//go:embed assets/aosp15_device.dirs
var embeddedDirManifest string

// parseListManifest reads one path per line (comments and blanks skipped).
func parseListManifest(text string) []string {
	var out []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out
}

var bundleEmptyDirs = parseListManifest(embeddedDirManifest)

// pathsUnder returns the entries of a path list that lie inside relPath.
func pathsUnder(list []string, relPath string) []string {
	relPath = strings.Trim(relPath, "/")
	var out []string
	for _, p := range list {
		if p == relPath || strings.HasPrefix(p, relPath+"/") {
			out = append(out, p)
		}
	}
	return out
}

// symlinksUnder returns the manifest entries whose link path is inside relPath.
func symlinksUnder(relPath string) []bundleSymlink {
	relPath = strings.Trim(relPath, "/")
	var out []bundleSymlink
	for _, l := range bundleSymlinks {
		if l.Path == relPath || strings.HasPrefix(l.Path, relPath+"/") {
			out = append(out, l)
		}
	}
	return out
}

// materializeSymlink recreates one bundle symlink under outRoot. No-clobber. A filesystem that
// refuses symlinks gets the target's bytes copied instead, when the target is inside the tree —
// the include still resolves, which is the point.
func materializeSymlink(outRoot string, l bundleSymlink) (bool, error) {
	dst := filepath.Join(outRoot, filepath.FromSlash(l.Path))
	if _, err := os.Lstat(dst); err == nil {
		return false, nil // no-clobber, symlink or real file
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return false, err
	}
	if err := os.Symlink(filepath.FromSlash(l.Target), dst); err == nil {
		return true, nil
	}
	src := filepath.Join(filepath.Dir(dst), filepath.FromSlash(l.Target))
	b, rerr := os.ReadFile(src)
	if rerr != nil {
		return false, fmt.Errorf("symlink %s -> %s: %w", l.Path, l.Target, rerr)
	}
	if werr := os.WriteFile(dst, b, 0o644); werr != nil {
		return false, werr
	}
	return true, nil
}

// Provenance of every top-level bundle directory: one line per directory, "<path> <AOSP tag>".
// Everything is android-15.0.0_r36 except tegu (Pixel 9a), whose tree exists only under
// android-15.0.0_r31; cross-tag reconciliations live in assets/reconcile (reconcile.go).
//
//go:embed assets/aosp15_device.sources
var embeddedSourcesTable string

// bundleSourceTag returns the AOSP tag a bundle directory (e.g. "device/google/tegu") was taken
// from, or "" when the directory is not listed.
func bundleSourceTag(dir string) string {
	dir = strings.Trim(dir, "/")
	for _, line := range strings.Split(embeddedSourcesTable, "\n") {
		f := strings.Fields(line)
		if len(f) >= 2 && !strings.HasPrefix(f[0], "#") && strings.Trim(f[0], "/") == dir {
			return f[1]
		}
	}
	return ""
}

// embeddedFileMode is the on-disk mode materializeEmbedded gives bundle path p.
func embeddedFileMode(p string) os.FileMode {
	if embeddedExecutables[p] {
		return 0o755
	}
	return 0o644
}

type bundleEntry struct {
	Path   string
	Size   int64
	SHA256 string
}

// parseBundleManifest reads "<sha256> <size> <path>" lines (comments and blanks skipped).
func parseBundleManifest(text string) []bundleEntry {
	var out []bundleEntry
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		f := strings.SplitN(line, " ", 3)
		if len(f) != 3 {
			continue
		}
		n, err := strconv.ParseInt(f[1], 10, 64)
		if err != nil {
			continue
		}
		out = append(out, bundleEntry{Path: f[2], Size: n, SHA256: f[0]})
	}
	return out
}

var bundleEntries = parseBundleManifest(embeddedBundleManifest)

// bundleID identifies the bundle this binary expects: the hash of its manifest, shortened.
func bundleID() string {
	h := sha256.Sum256([]byte(embeddedBundleManifest))
	return hex.EncodeToString(h[:])[:16]
}

// verifyBundle checks that fsys holds every entry with the recorded size and sha256. It stops at
// the first mismatch; extra files in fsys are not an error (an export directory may carry the
// stamp and manifest sidecars).
func verifyBundle(entries []bundleEntry, fsys fs.FS) (checked int, err error) {
	for _, e := range entries {
		f, oerr := fsys.Open(e.Path)
		if oerr != nil {
			return checked, fmt.Errorf("bundle: %s: %w", e.Path, oerr)
		}
		h := sha256.New()
		n, cerr := io.Copy(h, f)
		f.Close()
		if cerr != nil {
			return checked, fmt.Errorf("bundle: %s: %w", e.Path, cerr)
		}
		if n != e.Size {
			return checked, fmt.Errorf("bundle: %s: size %d, manifest says %d", e.Path, n, e.Size)
		}
		if got := hex.EncodeToString(h.Sum(nil)); got != e.SHA256 {
			return checked, fmt.Errorf("bundle: %s: sha256 %s, manifest says %s", e.Path, got[:12], e.SHA256[:12])
		}
		checked++
	}
	return checked, nil
}

// missingBundle is the fs.FS in place when no content source is available: every Open fails with
// the message that says how to supply one.
type missingBundle struct{ reason string }

func (m missingBundle) Open(name string) (fs.File, error) {
	return nil, &fs.PathError{Op: "open", Path: name, Err: errors.New(m.reason)}
}

const noBundleHelp = "this binary was built without the bundle (-tags nobundle); supply it with -bundle-dir <dir> or -bundle-url <archive .tar.gz> (or $SLS_BUNDLE_DIR / $SLS_BUNDLE_URL); `bundle export` on a full binary produces the archive"

// embeddedFS is the bundle rooted like an AOSP tree ("device/google/lynx", not the assets/…
// prefix), whichever source supplied it. Callers address paths the same way against it as
// against a real tree.
var embeddedFS fs.FS = initialBundle()

// bundleSource names where embeddedFS came from, for logging.
var bundleSource = "builtin"

func initialBundle() fs.FS {
	if b := builtinBundle(); b != nil {
		return b
	}
	if d := os.Getenv("SLS_BUNDLE_DIR"); d != "" {
		if f, err := bundleFromDir(bundleEntries, bundleID(), d); err == nil {
			bundleSource = d
			return f
		}
	}
	if f, err := bundleFromDir(bundleEntries, bundleID(), filepath.Join(defaultBundleCache(), bundleID())); err == nil {
		bundleSource = "cache"
		return f
	}
	bundleSource = "none"
	return missingBundle{reason: noBundleHelp}
}

func bundleAvailable() bool {
	_, missing := embeddedFS.(missingBundle)
	return !missing
}

// defaultBundleCache is $XDG_CACHE_HOME/sovereign-lane-surgeon/bundle or ~/.cache/… .
func defaultBundleCache() string {
	base := os.Getenv("XDG_CACHE_HOME")
	if base == "" {
		if home, err := os.UserHomeDir(); err == nil {
			base = filepath.Join(home, ".cache")
		} else {
			base = os.TempDir()
		}
	}
	return filepath.Join(base, "sovereign-lane-surgeon", "bundle")
}

func stampName(id string) string { return ".sls-verified-" + id }

// bundleFromDir verifies dir against entries (once — a stamp file records success) and returns it.
func bundleFromDir(entries []bundleEntry, id, dir string) (fs.FS, error) {
	info, err := os.Stat(dir)
	if err != nil || !info.IsDir() {
		return nil, fmt.Errorf("bundle: %s is not a directory", dir)
	}
	fsys := os.DirFS(dir)
	if fileExists(filepath.Join(dir, stampName(id))) {
		return fsys, nil
	}
	if _, err := verifyBundle(entries, fsys); err != nil {
		return nil, err
	}
	_ = os.WriteFile(filepath.Join(dir, stampName(id)), []byte(time.Now().UTC().Format(time.RFC3339)+"\n"), 0o644)
	return fsys, nil
}

// useBundleDir makes dir the bundle for the rest of this run.
func useBundleDir(dir string) error {
	f, err := bundleFromDir(bundleEntries, bundleID(), dir)
	if err != nil {
		return err
	}
	embeddedFS, bundleSource = f, dir
	return nil
}

// resolveBundle applies the create flags: an explicit directory, else an explicit or
// environment URL when nothing else supplied the content. With required, a still-missing bundle
// is an error rather than a later "not present in the embedded asset bundle".
func resolveBundle(dir, url string, required bool) error {
	if dir != "" {
		return useBundleDir(dir)
	}
	if url == "" && !bundleAvailable() {
		url = os.Getenv("SLS_BUNDLE_URL")
	}
	if url != "" && (!bundleAvailable() || dir == "") && !bundleAvailable() {
		fmt.Printf("  bundle %s: fetching %s\n", bundleID(), url)
		d, err := fetchBundle(bundleEntries, bundleID(), url, defaultBundleCache())
		if err != nil {
			return err
		}
		return useBundleDir(d)
	}
	if required && !bundleAvailable() {
		return errors.New(noBundleHelp)
	}
	return nil
}

// fetchBundle downloads a .tar.gz into cacheRoot/<id>.tar.gz, extracts it to cacheRoot/<id>/ and
// verifies it. A directory that already verified is returned as is. Any mismatch removes the
// extraction so a corrupt or wrong archive can never be picked up silently later.
func fetchBundle(entries []bundleEntry, id, url, cacheRoot string) (string, error) {
	dir := filepath.Join(cacheRoot, id)
	if fileExists(filepath.Join(dir, stampName(id))) {
		return dir, nil
	}
	if err := os.MkdirAll(cacheRoot, 0o755); err != nil {
		return "", err
	}
	var rc io.ReadCloser
	if strings.HasPrefix(url, "http://") || strings.HasPrefix(url, "https://") {
		resp, err := http.Get(url)
		if err != nil {
			return "", fmt.Errorf("bundle: fetch %s: %w", url, err)
		}
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			return "", fmt.Errorf("bundle: fetch %s: HTTP %s", url, resp.Status)
		}
		rc = resp.Body
	} else {
		f, err := os.Open(url) // a local archive path works too
		if err != nil {
			return "", err
		}
		rc = f
	}
	defer rc.Close()
	_ = os.RemoveAll(dir)
	if err := extractBundleArchive(rc, dir); err != nil {
		_ = os.RemoveAll(dir)
		return "", err
	}
	if _, err := bundleFromDir(entries, id, dir); err != nil {
		_ = os.RemoveAll(dir)
		return "", fmt.Errorf("%w (the archive at %s is not bundle %s)", err, url, id)
	}
	return dir, nil
}

// extractBundleArchive unpacks a .tar.gz of bundle-relative paths under dir. Paths are cleaned and
// confined to dir; only regular files and directories are written (no links, no devices).
func extractBundleArchive(r io.Reader, dir string) error {
	gz, err := gzip.NewReader(r)
	if err != nil {
		return fmt.Errorf("bundle: archive: %w", err)
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		h, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return fmt.Errorf("bundle: archive: %w", err)
		}
		name := path.Clean(strings.TrimPrefix(h.Name, "./"))
		if name == "." || strings.HasPrefix(name, "../") || path.IsAbs(name) {
			continue
		}
		target := filepath.Join(dir, filepath.FromSlash(name))
		switch h.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeSymlink:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			link := filepath.Clean(h.Linkname)
			if filepath.IsAbs(link) || strings.HasPrefix(filepath.ToSlash(link), "../../../") {
				continue // never point outside the extraction root
			}
			_ = os.Remove(target)
			if err := os.Symlink(h.Linkname, target); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			mode := os.FileMode(0o644)
			if h.Mode&0o111 != 0 {
				mode = 0o755
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, mode)
			if err != nil {
				return err
			}
			if _, err := io.Copy(f, tr); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}
	}
}

// exportBundle writes entries from src as a .tar.gz (executables per the exec manifest, plus the
// symlinks embed dropped, as real tar symlink entries).
func exportBundle(entries []bundleEntry, src fs.FS, w io.Writer) error {
	gz := gzip.NewWriter(w)
	tw := tar.NewWriter(gz)
	for _, d := range bundleEmptyDirs {
		if err := tw.WriteHeader(&tar.Header{Name: d + "/", Mode: 0o755, Typeflag: tar.TypeDir}); err != nil {
			return err
		}
	}
	for _, l := range bundleSymlinks {
		if err := tw.WriteHeader(&tar.Header{Name: l.Path, Mode: 0o777, Typeflag: tar.TypeSymlink, Linkname: l.Target}); err != nil {
			return err
		}
	}
	for _, e := range entries {
		b, err := fs.ReadFile(src, e.Path)
		if err != nil {
			return err
		}
		mode := int64(0o644)
		if embeddedExecutables[e.Path] {
			mode = 0o755
		}
		if err := tw.WriteHeader(&tar.Header{Name: e.Path, Mode: mode, Size: int64(len(b)), Typeflag: tar.TypeReg}); err != nil {
			return err
		}
		if _, err := tw.Write(b); err != nil {
			return err
		}
	}
	if err := tw.Close(); err != nil {
		return err
	}
	return gz.Close()
}

// hasEmbeddedPath reports whether relPath (fs.FS form, forward-slashed — e.g.
// "device/google/lynx") exists in the bundle.
func hasEmbeddedPath(relPath string) bool {
	_, err := fs.Stat(embeddedFS, relPath)
	return err == nil
}

// materializeEmbedded extracts embeddedFS's relPath onto outRoot/relPath on real disk. No-clobber
// (an existing target file always wins), matching mirrorStockTree/copyDeviceFamilyTree's safety
// property — safe to call speculatively before either of them runs.
func materializeEmbedded(relPath, outRoot string) (copied int, err error) {
	if _, statErr := fs.Stat(embeddedFS, relPath); statErr != nil {
		if !bundleAvailable() {
			return 0, errors.New(noBundleHelp)
		}
		return 0, fmt.Errorf("%s not present in the embedded asset bundle", relPath)
	}
	dst := filepath.Join(outRoot, filepath.FromSlash(relPath))
	walkErr := fs.WalkDir(embeddedFS, relPath, func(p string, d fs.DirEntry, e error) error {
		if e != nil {
			return e
		}
		rel, rerr := filepath.Rel(filepath.FromSlash(relPath), filepath.FromSlash(p))
		if rerr != nil {
			return rerr
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if _, statErr := os.Stat(target); statErr == nil || neutralizedByBak(target) {
			return nil // no-clobber
		}
		if mirrorSkipsMakefile(outRoot, p, embeddedFS) {
			return nil // the target denylists it (overlay-replaced or an empty wrapper) — never lands
		}
		b, rerr := fs.ReadFile(embeddedFS, p)
		if rerr != nil {
			return rerr
		}
		if merr := os.MkdirAll(filepath.Dir(target), 0o755); merr != nil {
			return merr
		}
		if werr := os.WriteFile(target, b, embeddedFileMode(p)); werr != nil {
			return werr
		}
		copied++
		return nil
	})
	if walkErr != nil {
		return copied, walkErr
	}
	// The empty directories embed dropped: created before the links, which may point into them.
	for _, d := range pathsUnder(bundleEmptyDirs, relPath) {
		if err := os.MkdirAll(filepath.Join(outRoot, filepath.FromSlash(d)), 0o755); err != nil {
			return copied, err
		}
	}
	// The symlinks embed dropped (see embeddedSymlinkManifest), after the files they point at.
	for _, l := range symlinksUnder(relPath) {
		made, serr := materializeSymlink(outRoot, l)
		if serr != nil {
			return copied, serr
		}
		if made {
			copied++
		}
	}
	return copied, nil
}

// sliceFlag collects a repeatable string flag.
type sliceFlag []string

func (s *sliceFlag) String() string     { return strings.Join(*s, ",") }
func (s *sliceFlag) Set(v string) error { *s = append(*s, v); return nil }

// verifyBundleExtras checks a materialized bundle directory for what the content manifest cannot
// express: executable bits, symlinks (and their targets) and empty directories.
func verifyBundleExtras(dir string) []string {
	var problems []string
	for p := range embeddedExecutables {
		fi, err := os.Stat(filepath.Join(dir, filepath.FromSlash(p)))
		if err != nil {
			problems = append(problems, "missing executable: "+p)
		} else if fi.Mode()&0o111 == 0 {
			problems = append(problems, "not executable: "+p)
		}
	}
	for _, l := range bundleSymlinks {
		full := filepath.Join(dir, filepath.FromSlash(l.Path))
		target, err := os.Readlink(full)
		if err != nil {
			if _, serr := os.Stat(full); serr == nil {
				continue // materialized as a copy: a filesystem that refuses symlinks
			}
			problems = append(problems, "missing symlink: "+l.Path)
			continue
		}
		if filepath.ToSlash(target) != l.Target {
			problems = append(problems, "symlink "+l.Path+" -> "+filepath.ToSlash(target)+", want "+l.Target)
		}
	}
	for _, d := range bundleEmptyDirs {
		if fi, err := os.Stat(filepath.Join(dir, filepath.FromSlash(d))); err != nil || !fi.IsDir() {
			problems = append(problems, "missing directory: "+d)
		}
	}
	sort.Strings(problems)
	return problems
}

// cmdBundle: info | verify [-dir] | export -out <dir> | audit -source <tree>.
func cmdBundle(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "bundle: info | verify [-dir <dir>] | export -out <dir> | audit -source <aosp tree>")
		return 2
	}
	sub, rest := args[0], args[1:]
	fs := flag.NewFlagSet("bundle "+sub, flag.ExitOnError)
	dir := fs.String("dir", "", "verify: a bundle directory instead of the active source")
	out := fs.String("out", "", "export: directory to write sls-bundle-<id>.tar.gz and .sha256 into")
	var sources sliceFlag
	fs.Var(&sources, "source", "audit: an AOSP tree the bundle was cut from (repeatable — the bundle spans android-15.0.0_r36 and, for tegu, r31)")
	allowUnaudited := fs.Bool("allow-unaudited", false, "audit: succeed when some directories have no -source tree to compare against (they are still listed)")
	_ = fs.Parse(rest)
	var total int64
	for _, e := range bundleEntries {
		total += e.Size
	}
	switch sub {
	case "audit":
		if len(sources) == 0 {
			fmt.Fprintln(os.Stderr, "bundle audit: -source <aosp tree> is required (repeatable; see assets/aosp15_device.sources for which tag each directory came from)")
			return 2
		}
		tops := bundleTopDirs()
		covered := map[string]bool{}
		rc := 0
		for _, src := range sources {
			res, err := auditBundleAgainstSource(src, tops)
			if err != nil {
				fmt.Fprintf(os.Stderr, "bundle audit: %s: %v\n", src, err)
				return 1
			}
			for _, d := range res.Audited {
				covered[d] = true
			}
			fmt.Printf("bundle audit %s\n  %d directories, %d entries compared, %d excluded by design\n",
				src, len(res.Audited), res.Checked, res.Excluded)
			if len(res.Findings) == 0 {
				fmt.Println("  OK — content, executable bits, symlinks and empty directories all match")
				continue
			}
			rc = 1
			byClass := map[string]int{}
			for _, f := range res.Findings {
				byClass[f.Class]++
			}
			var classes []string
			for c := range byClass {
				classes = append(classes, c)
			}
			sort.Strings(classes)
			for _, c := range classes {
				fmt.Printf("  %s: %d\n", c, byClass[c])
			}
			for i, f := range res.Findings {
				if i == 40 {
					fmt.Printf("  ... and %d more\n", len(res.Findings)-40)
					break
				}
				fmt.Printf("    [%s] %s — %s\n", f.Class, f.Path, f.Note)
			}
		}
		var unaudited []string
		for _, d := range tops {
			if !covered[d] {
				unaudited = append(unaudited, d)
			}
		}
		diverged := rc != 0
		if len(unaudited) > 0 {
			fmt.Printf("  ! %d of %d directories were not audited — no -source tree carries them: %s\n",
				len(unaudited), len(tops), strings.Join(unaudited, " "))
			for _, d := range unaudited {
				if tag := bundleSourceTag(d); tag != "" {
					fmt.Printf("      %s came from %s\n", d, tag)
				}
			}
			fmt.Println("    Pass that tree with another -source, or -allow-unaudited to accept partial coverage.")
			if !*allowUnaudited {
				rc = 1
			}
		}
		switch {
		case diverged:
			fmt.Println("VERDICT: DIVERGENCE — regenerate with `go generate ./...` if the source moved, or investigate the findings above")
		case len(unaudited) == 0:
			fmt.Printf("VERDICT: faithful — all %d directories match their source across every property go:embed can lose\n", len(covered))
		default:
			fmt.Printf("VERDICT: no divergence in the %d directories audited; %d unaudited (source tree not provided)\n", len(covered), len(unaudited))
		}
		return rc
	case "info":
		fmt.Printf("bundle id %s: %d files (%d MB), %d executable, %d symlinks, %d empty dirs; source: %s; cache: %s\n",
			bundleID(), len(bundleEntries), total/1e6, len(embeddedExecutables), len(bundleSymlinks), len(bundleEmptyDirs),
			bundleSource, filepath.Join(defaultBundleCache(), bundleID()))
		return 0
	case "verify":
		src := embeddedFS
		if *dir != "" {
			src = os.DirFS(*dir)
		} else if !bundleAvailable() {
			fmt.Fprintln(os.Stderr, "bundle verify:", noBundleHelp)
			return 1
		}
		n, err := verifyBundle(bundleEntries, src)
		if err != nil {
			fmt.Fprintf(os.Stderr, "bundle verify: FAILED after %d files: %v\n", n, err)
			return 1
		}
		fmt.Printf("bundle verify: OK — %d files match manifest %s\n", n, bundleID())
		// A directory bundle can also be checked for the properties embed drops; an embedded
		// bundle carries them in the manifests by construction.
		if *dir != "" {
			if problems := verifyBundleExtras(*dir); len(problems) > 0 {
				for _, p := range problems {
					fmt.Fprintln(os.Stderr, "  "+p)
				}
				fmt.Fprintf(os.Stderr, "bundle verify: FAILED — %d executable/symlink/directory mismatches\n", len(problems))
				return 1
			}
			fmt.Printf("  + %d executable bits, %d symlinks, %d empty directories all present\n",
				len(embeddedExecutables), len(bundleSymlinks), len(bundleEmptyDirs))
		}
		if *dir != "" {
			_ = os.WriteFile(filepath.Join(*dir, stampName(bundleID())), []byte(time.Now().UTC().Format(time.RFC3339)+"\n"), 0o644)
		}
		return 0
	case "export":
		if *out == "" {
			fmt.Fprintln(os.Stderr, "bundle export: -out <dir> is required")
			return 2
		}
		if !bundleAvailable() {
			fmt.Fprintln(os.Stderr, "bundle export:", noBundleHelp)
			return 1
		}
		if err := os.MkdirAll(*out, 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "bundle export:", err)
			return 1
		}
		archive := filepath.Join(*out, "sls-bundle-"+bundleID()+".tar.gz")
		f, err := os.Create(archive)
		if err != nil {
			fmt.Fprintln(os.Stderr, "bundle export:", err)
			return 1
		}
		if err := exportBundle(bundleEntries, embeddedFS, f); err != nil {
			f.Close()
			fmt.Fprintln(os.Stderr, "bundle export:", err)
			return 1
		}
		f.Close()
		manifest := filepath.Join(*out, "sls-bundle-"+bundleID()+".sha256")
		_ = os.WriteFile(manifest, []byte(embeddedBundleManifest), 0o644)
		fi, _ := os.Stat(archive)
		fmt.Printf("bundle export: %s (%d MB, %d files) + %s\n", archive, fi.Size()/1e6, len(bundleEntries), manifest)
		fmt.Printf("  publish both; a -tags nobundle binary of this revision fetches with -bundle-url <archive URL> and verifies against manifest %s\n", bundleID())
		return 0
	}
	fmt.Fprintf(os.Stderr, "bundle: unknown subcommand %q\n", sub)
	return 2
}
