// Copyright 2026 The Android Open Source Project
// Copyright 2026 Sovereign Lane Surgeon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// bundle.go — the bundle as CONTENT-ADDRESSED data, separable from the binary.
//
// The binary always embeds the bundle MANIFEST (assets/aosp15_device.sha256: sha256, size and
// path of all ~7100 files, regenerated by `go generate`); bundleID is the hash of that manifest.
// The bundle CONTENT comes from the first of these that is present and verifies:
//
//	builtin        the default build embeds it (embeddedassets.go)
//	-bundle-dir    a directory (or $SLS_BUNDLE_DIR)
//	cache          $XDG_CACHE_HOME/sovereign-lane-surgeon/bundle/<id>/ (or ~/.cache/…)
//	-bundle-url    a .tar.gz fetched into the cache (or $SLS_BUNDLE_URL)
//
// Every non-builtin source is verified file by file against the manifest before it is used
// (a stamp file records a verified directory so the hash pass runs once); a directory or
// archive that does not match the manifest this binary was built with is refused, whatever
// its name. `bundle export` writes the archive + manifest from a builtin binary for publishing,
// so `go build -tags nobundle` (~5MB) plus one published archive per bundle id replaces the
// ~510MB binary for distribution and CI.

//go:generate go run ./cmd/bundlemanifest
//go:embed assets/aosp15_device.sha256
var embeddedBundleManifest string

// embed.FS carries file contents only: every embedded file stats as 0444, so the executable bit
// AOSP's scripts rely on (kati runs device/google/tangorpro/uwb/country_conf_gen.sh via $(shell)
// and errors "Permission denied" at 0644) has to travel separately. cmd/execmanifest regenerates
// this list from the on-disk assets tree; materializeEmbedded writes listed paths as 0755, and
// exportBundle records them as 0755 in the archive.
//
//go:generate go run ./cmd/execmanifest
//go:embed assets/aosp15_device.exec
var embeddedExecManifest string

// embeddedExecutables is the exec manifest as a set of bundle-relative, forward-slashed paths.
var embeddedExecutables = func() map[string]bool {
	set := map[string]bool{}
	for _, line := range strings.Split(embeddedExecManifest, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		set[line] = true
	}
	return set
}()

// Provenance of every top-level bundle directory: one line per directory, "<path> <AOSP tag>".
// Everything is android-15.0.0_r36 except tegu (Pixel 9a), whose tree exists only under
// android-15.0.0_r31; cross-tag reconciliations live in assets/reconcile (reconcile.go).
//
//go:embed assets/aosp15_device.sources
var embeddedSourcesTable string

// bundleSourceTag returns the AOSP tag a bundle directory (e.g. "device/google/tegu") was taken
// from, or "" when the directory is not listed.
func bundleSourceTag(dir string) string {
	dir = strings.Trim(dir, "/")
	for _, line := range strings.Split(embeddedSourcesTable, "\n") {
		f := strings.Fields(line)
		if len(f) >= 2 && !strings.HasPrefix(f[0], "#") && strings.Trim(f[0], "/") == dir {
			return f[1]
		}
	}
	return ""
}

// embeddedFileMode is the on-disk mode materializeEmbedded gives bundle path p.
func embeddedFileMode(p string) os.FileMode {
	if embeddedExecutables[p] {
		return 0o755
	}
	return 0o644
}

type bundleEntry struct {
	Path   string
	Size   int64
	SHA256 string
}

// parseBundleManifest reads "<sha256> <size> <path>" lines (comments and blanks skipped).
func parseBundleManifest(text string) []bundleEntry {
	var out []bundleEntry
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		f := strings.SplitN(line, " ", 3)
		if len(f) != 3 {
			continue
		}
		n, err := strconv.ParseInt(f[1], 10, 64)
		if err != nil {
			continue
		}
		out = append(out, bundleEntry{Path: f[2], Size: n, SHA256: f[0]})
	}
	return out
}

var bundleEntries = parseBundleManifest(embeddedBundleManifest)

// bundleID identifies the bundle this binary expects: the hash of its manifest, shortened.
func bundleID() string {
	h := sha256.Sum256([]byte(embeddedBundleManifest))
	return hex.EncodeToString(h[:])[:16]
}

// verifyBundle checks that fsys holds every entry with the recorded size and sha256. It stops at
// the first mismatch; extra files in fsys are not an error (an export directory may carry the
// stamp and manifest sidecars).
func verifyBundle(entries []bundleEntry, fsys fs.FS) (checked int, err error) {
	for _, e := range entries {
		f, oerr := fsys.Open(e.Path)
		if oerr != nil {
			return checked, fmt.Errorf("bundle: %s: %w", e.Path, oerr)
		}
		h := sha256.New()
		n, cerr := io.Copy(h, f)
		f.Close()
		if cerr != nil {
			return checked, fmt.Errorf("bundle: %s: %w", e.Path, cerr)
		}
		if n != e.Size {
			return checked, fmt.Errorf("bundle: %s: size %d, manifest says %d", e.Path, n, e.Size)
		}
		if got := hex.EncodeToString(h.Sum(nil)); got != e.SHA256 {
			return checked, fmt.Errorf("bundle: %s: sha256 %s, manifest says %s", e.Path, got[:12], e.SHA256[:12])
		}
		checked++
	}
	return checked, nil
}

// missingBundle is the fs.FS in place when no content source is available: every Open fails with
// the message that says how to supply one.
type missingBundle struct{ reason string }

func (m missingBundle) Open(name string) (fs.File, error) {
	return nil, &fs.PathError{Op: "open", Path: name, Err: errors.New(m.reason)}
}

const noBundleHelp = "this binary was built without the bundle (-tags nobundle); supply it with -bundle-dir <dir> or -bundle-url <archive .tar.gz> (or $SLS_BUNDLE_DIR / $SLS_BUNDLE_URL); `bundle export` on a full binary produces the archive"

// embeddedFS is the bundle rooted like an AOSP tree ("device/google/lynx", not the assets/…
// prefix), whichever source supplied it. Callers address paths the same way against it as
// against a real tree.
var embeddedFS fs.FS = initialBundle()

// bundleSource names where embeddedFS came from, for logging.
var bundleSource = "builtin"

func initialBundle() fs.FS {
	if b := builtinBundle(); b != nil {
		return b
	}
	if d := os.Getenv("SLS_BUNDLE_DIR"); d != "" {
		if f, err := bundleFromDir(bundleEntries, bundleID(), d); err == nil {
			bundleSource = d
			return f
		}
	}
	if f, err := bundleFromDir(bundleEntries, bundleID(), filepath.Join(defaultBundleCache(), bundleID())); err == nil {
		bundleSource = "cache"
		return f
	}
	bundleSource = "none"
	return missingBundle{reason: noBundleHelp}
}

func bundleAvailable() bool {
	_, missing := embeddedFS.(missingBundle)
	return !missing
}

// defaultBundleCache is $XDG_CACHE_HOME/sovereign-lane-surgeon/bundle or ~/.cache/… .
func defaultBundleCache() string {
	base := os.Getenv("XDG_CACHE_HOME")
	if base == "" {
		if home, err := os.UserHomeDir(); err == nil {
			base = filepath.Join(home, ".cache")
		} else {
			base = os.TempDir()
		}
	}
	return filepath.Join(base, "sovereign-lane-surgeon", "bundle")
}

func stampName(id string) string { return ".sls-verified-" + id }

// bundleFromDir verifies dir against entries (once — a stamp file records success) and returns it.
func bundleFromDir(entries []bundleEntry, id, dir string) (fs.FS, error) {
	info, err := os.Stat(dir)
	if err != nil || !info.IsDir() {
		return nil, fmt.Errorf("bundle: %s is not a directory", dir)
	}
	fsys := os.DirFS(dir)
	if fileExists(filepath.Join(dir, stampName(id))) {
		return fsys, nil
	}
	if _, err := verifyBundle(entries, fsys); err != nil {
		return nil, err
	}
	_ = os.WriteFile(filepath.Join(dir, stampName(id)), []byte(time.Now().UTC().Format(time.RFC3339)+"\n"), 0o644)
	return fsys, nil
}

// useBundleDir makes dir the bundle for the rest of this run.
func useBundleDir(dir string) error {
	f, err := bundleFromDir(bundleEntries, bundleID(), dir)
	if err != nil {
		return err
	}
	embeddedFS, bundleSource = f, dir
	return nil
}

// resolveBundle applies the create flags: an explicit directory, else an explicit or
// environment URL when nothing else supplied the content. With required, a still-missing bundle
// is an error rather than a later "not present in the embedded asset bundle".
func resolveBundle(dir, url string, required bool) error {
	if dir != "" {
		return useBundleDir(dir)
	}
	if url == "" && !bundleAvailable() {
		url = os.Getenv("SLS_BUNDLE_URL")
	}
	if url != "" && (!bundleAvailable() || dir == "") && !bundleAvailable() {
		fmt.Printf("  bundle %s: fetching %s\n", bundleID(), url)
		d, err := fetchBundle(bundleEntries, bundleID(), url, defaultBundleCache())
		if err != nil {
			return err
		}
		return useBundleDir(d)
	}
	if required && !bundleAvailable() {
		return errors.New(noBundleHelp)
	}
	return nil
}

// fetchBundle downloads a .tar.gz into cacheRoot/<id>.tar.gz, extracts it to cacheRoot/<id>/ and
// verifies it. A directory that already verified is returned as is. Any mismatch removes the
// extraction so a corrupt or wrong archive can never be picked up silently later.
func fetchBundle(entries []bundleEntry, id, url, cacheRoot string) (string, error) {
	dir := filepath.Join(cacheRoot, id)
	if fileExists(filepath.Join(dir, stampName(id))) {
		return dir, nil
	}
	if err := os.MkdirAll(cacheRoot, 0o755); err != nil {
		return "", err
	}
	var rc io.ReadCloser
	if strings.HasPrefix(url, "http://") || strings.HasPrefix(url, "https://") {
		resp, err := http.Get(url)
		if err != nil {
			return "", fmt.Errorf("bundle: fetch %s: %w", url, err)
		}
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			return "", fmt.Errorf("bundle: fetch %s: HTTP %s", url, resp.Status)
		}
		rc = resp.Body
	} else {
		f, err := os.Open(url) // a local archive path works too
		if err != nil {
			return "", err
		}
		rc = f
	}
	defer rc.Close()
	_ = os.RemoveAll(dir)
	if err := extractBundleArchive(rc, dir); err != nil {
		_ = os.RemoveAll(dir)
		return "", err
	}
	if _, err := bundleFromDir(entries, id, dir); err != nil {
		_ = os.RemoveAll(dir)
		return "", fmt.Errorf("%w (the archive at %s is not bundle %s)", err, url, id)
	}
	return dir, nil
}

// extractBundleArchive unpacks a .tar.gz of bundle-relative paths under dir. Paths are cleaned and
// confined to dir; only regular files and directories are written (no links, no devices).
func extractBundleArchive(r io.Reader, dir string) error {
	gz, err := gzip.NewReader(r)
	if err != nil {
		return fmt.Errorf("bundle: archive: %w", err)
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		h, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return fmt.Errorf("bundle: archive: %w", err)
		}
		name := path.Clean(strings.TrimPrefix(h.Name, "./"))
		if name == "." || strings.HasPrefix(name, "../") || path.IsAbs(name) {
			continue
		}
		target := filepath.Join(dir, filepath.FromSlash(name))
		switch h.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			mode := os.FileMode(0o644)
			if h.Mode&0o111 != 0 {
				mode = 0o755
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, mode)
			if err != nil {
				return err
			}
			if _, err := io.Copy(f, tr); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}
	}
}

// exportBundle writes entries from src as a .tar.gz (executables per the exec manifest).
func exportBundle(entries []bundleEntry, src fs.FS, w io.Writer) error {
	gz := gzip.NewWriter(w)
	tw := tar.NewWriter(gz)
	for _, e := range entries {
		b, err := fs.ReadFile(src, e.Path)
		if err != nil {
			return err
		}
		mode := int64(0o644)
		if embeddedExecutables[e.Path] {
			mode = 0o755
		}
		if err := tw.WriteHeader(&tar.Header{Name: e.Path, Mode: mode, Size: int64(len(b)), Typeflag: tar.TypeReg}); err != nil {
			return err
		}
		if _, err := tw.Write(b); err != nil {
			return err
		}
	}
	if err := tw.Close(); err != nil {
		return err
	}
	return gz.Close()
}

// hasEmbeddedPath reports whether relPath (fs.FS form, forward-slashed — e.g.
// "device/google/lynx") exists in the bundle.
func hasEmbeddedPath(relPath string) bool {
	_, err := fs.Stat(embeddedFS, relPath)
	return err == nil
}

// materializeEmbedded extracts embeddedFS's relPath onto outRoot/relPath on real disk. No-clobber
// (an existing target file always wins), matching mirrorStockTree/copyDeviceFamilyTree's safety
// property — safe to call speculatively before either of them runs.
func materializeEmbedded(relPath, outRoot string) (copied int, err error) {
	if _, statErr := fs.Stat(embeddedFS, relPath); statErr != nil {
		if !bundleAvailable() {
			return 0, errors.New(noBundleHelp)
		}
		return 0, fmt.Errorf("%s not present in the embedded asset bundle", relPath)
	}
	dst := filepath.Join(outRoot, filepath.FromSlash(relPath))
	walkErr := fs.WalkDir(embeddedFS, relPath, func(p string, d fs.DirEntry, e error) error {
		if e != nil {
			return e
		}
		rel, rerr := filepath.Rel(filepath.FromSlash(relPath), filepath.FromSlash(p))
		if rerr != nil {
			return rerr
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if _, statErr := os.Stat(target); statErr == nil || neutralizedByBak(target) {
			return nil // no-clobber
		}
		if mirrorSkipsMakefile(outRoot, p, embeddedFS) {
			return nil // the target denylists it (overlay-replaced or an empty wrapper) — never lands
		}
		b, rerr := fs.ReadFile(embeddedFS, p)
		if rerr != nil {
			return rerr
		}
		if merr := os.MkdirAll(filepath.Dir(target), 0o755); merr != nil {
			return merr
		}
		if werr := os.WriteFile(target, b, embeddedFileMode(p)); werr != nil {
			return werr
		}
		copied++
		return nil
	})
	return copied, walkErr
}

// cmdBundle: info | verify [-dir] | export -out <dir>.
func cmdBundle(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "bundle: info | verify [-dir <dir>] | export -out <dir>")
		return 2
	}
	sub, rest := args[0], args[1:]
	fs := flag.NewFlagSet("bundle "+sub, flag.ExitOnError)
	dir := fs.String("dir", "", "verify: a bundle directory instead of the active source")
	out := fs.String("out", "", "export: directory to write sls-bundle-<id>.tar.gz and .sha256 into")
	_ = fs.Parse(rest)
	var total int64
	for _, e := range bundleEntries {
		total += e.Size
	}
	switch sub {
	case "info":
		fmt.Printf("bundle id %s: %d files, %d MB; source: %s; cache: %s\n", bundleID(), len(bundleEntries), total/1e6, bundleSource, filepath.Join(defaultBundleCache(), bundleID()))
		return 0
	case "verify":
		src := embeddedFS
		if *dir != "" {
			src = os.DirFS(*dir)
		} else if !bundleAvailable() {
			fmt.Fprintln(os.Stderr, "bundle verify:", noBundleHelp)
			return 1
		}
		n, err := verifyBundle(bundleEntries, src)
		if err != nil {
			fmt.Fprintf(os.Stderr, "bundle verify: FAILED after %d files: %v\n", n, err)
			return 1
		}
		fmt.Printf("bundle verify: OK — %d files match manifest %s\n", n, bundleID())
		if *dir != "" {
			_ = os.WriteFile(filepath.Join(*dir, stampName(bundleID())), []byte(time.Now().UTC().Format(time.RFC3339)+"\n"), 0o644)
		}
		return 0
	case "export":
		if *out == "" {
			fmt.Fprintln(os.Stderr, "bundle export: -out <dir> is required")
			return 2
		}
		if !bundleAvailable() {
			fmt.Fprintln(os.Stderr, "bundle export:", noBundleHelp)
			return 1
		}
		if err := os.MkdirAll(*out, 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "bundle export:", err)
			return 1
		}
		archive := filepath.Join(*out, "sls-bundle-"+bundleID()+".tar.gz")
		f, err := os.Create(archive)
		if err != nil {
			fmt.Fprintln(os.Stderr, "bundle export:", err)
			return 1
		}
		if err := exportBundle(bundleEntries, embeddedFS, f); err != nil {
			f.Close()
			fmt.Fprintln(os.Stderr, "bundle export:", err)
			return 1
		}
		f.Close()
		manifest := filepath.Join(*out, "sls-bundle-"+bundleID()+".sha256")
		_ = os.WriteFile(manifest, []byte(embeddedBundleManifest), 0o644)
		fi, _ := os.Stat(archive)
		fmt.Printf("bundle export: %s (%d MB, %d files) + %s\n", archive, fi.Size()/1e6, len(bundleEntries), manifest)
		fmt.Printf("  publish both; a -tags nobundle binary of this revision fetches with -bundle-url <archive URL> and verifies against manifest %s\n", bundleID())
		return 0
	}
	fmt.Fprintf(os.Stderr, "bundle: unknown subcommand %q\n", sub)
	return 2
}
