// Copyright 2026 The Android Open Source Project
// Copyright 2026 Sovereign Lane Surgeon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fakeAospRoot builds an isolated tree with just the 3 soong files (scratch copies mirroring the
// real slice/func shapes) so stage→apply can be exercised without touching any live tree.
func fakeAospRoot(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	files := map[string]string{
		"build/soong/java/aar.go": `package java

import "strings"

func isLaneLunch(productName string) bool {
	for _, suffix := range []string{"_holo", "_nexus", "_nexusm"} {
		if strings.HasSuffix(productName, suffix) {
			return true
		}
	}
	return false
}
`,
		"build/soong/android/visibility.go": `package android

func laneCanonicalPkgs(pkg string) []string {
	for _, suf := range []string{"-holo", "-nexusm", "-nexus"} {
		_ = suf
	}
	return nil
}
`,
		"build/soong/ui/build/finder.go": `package build

import "strings"

func isNexusMNexus(config Config) bool { return false }

func isOtherLaneBp(bp string) bool {
	for _, comp := range strings.Split(bp, "/") {
		if strings.HasSuffix(comp, "-nexusm") ||
			strings.HasSuffix(comp, "-nexus") {
			return true
		}
	}
	return false
}

func runFinder() {
	androidBps := find()
	if len(androidBps) == 0 {
		panic("none")
	}
	_ = androidBps
}
`,
	}
	for rel, content := range files {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

// TestStageThenApply: stage patches for a fresh lane, confirm the live files are UNTOUCHED and
// the staging dir holds the patched copies; then apply and confirm the live files are patched,
// a snapshot exists, and staging is cleared.
func TestStageThenApply(t *testing.T) {
	root := fakeAospRoot(t)
	cfg := deriveLane("aurora", true, nil, true, true, "")

	staged, fatal := stageSoongPatches(cfg, root)
	if fatal {
		t.Fatal("stage returned fatal")
	}
	if staged != 3 {
		t.Errorf("expected 3 staged files, got %d", staged)
	}

	// Live files must be untouched after staging.
	aarLive, _ := os.ReadFile(filepath.Join(root, "build/soong/java/aar.go"))
	if strings.Contains(string(aarLive), "_aurora") {
		t.Error("staging mutated the live aar.go — must not")
	}
	// Staging holds the patched copy.
	aarStage, err := os.ReadFile(filepath.Join(root, stageDir, "build/soong/java/aar.go"))
	if err != nil {
		t.Fatal("aar.go not staged:", err)
	}
	if !strings.Contains(string(aarStage), `"_holo", "_nexus", "_nexusm", "_aurora"`) {
		t.Error("staged aar.go missing _aurora registration")
	}

	// Apply.
	if rc := applyStaged(root); rc != 0 {
		t.Fatalf("apply returned %d", rc)
	}
	// Live files now patched.
	for _, probe := range []struct{ rel, want string }{
		{"build/soong/java/aar.go", `"_aurora"`},
		{"build/soong/android/visibility.go", `"-aurora"`},
		{"build/soong/ui/build/finder.go", "func isAuroraLane(config Config) bool"},
		{"build/soong/ui/build/finder.go", "androidBps = applyAuroraBpRoutes(ctx, config, androidBps)"},
		{"build/soong/ui/build/finder.go", `strings.HasSuffix(comp, "-aurora")`}, // cross-cut into isOtherLaneBp
	} {
		b, _ := os.ReadFile(filepath.Join(root, probe.rel))
		if !strings.Contains(string(b), probe.want) {
			t.Errorf("%s: applied file missing %q", probe.rel, probe.want)
		}
	}
	// Staging cleared.
	if _, err := os.Stat(filepath.Join(root, stageDir)); !os.IsNotExist(err) {
		t.Error("staging dir not cleared after apply")
	}
	// A snapshot dir exists with the pre-apply aar.go (no _aurora).
	snaps, _ := filepath.Glob(filepath.Join(root, snapshotDir, "*", "build/soong/java/aar.go"))
	if len(snaps) != 1 {
		t.Fatalf("expected 1 aar.go snapshot, got %d", len(snaps))
	}
	snap, _ := os.ReadFile(snaps[0])
	if strings.Contains(string(snap), "_aurora") {
		t.Error("snapshot should be the PRE-apply file (no _aurora)")
	}

	// Route manifest generated by a full create-out would live at .aurora/… — check emit directly.
	mf, err := emitRouteManifest(cfg.Name, cfg.CamelCase, "")
	if err != nil || !strings.Contains(string(mf), `"lane": "aurora"`) {
		t.Errorf("route manifest emit: %v", err)
	}
}

// TestMultiLaneStageChain: staging 3 lanes accumulates (chain-aware read) — all 3 register and
// each lane's other-lane func blinds the other two.
func TestMultiLaneStageChain(t *testing.T) {
	root := fakeAospRoot(t)
	for _, lane := range []string{"testing1", "testing2", "testing3"} {
		cfg := deriveLane(lane, true, nil, true, true, "")
		if _, fatal := stageSoongPatches(cfg, root); fatal {
			t.Fatalf("%s: fatal", lane)
		}
	}
	aar, _ := os.ReadFile(filepath.Join(root, stageDir, "build/soong/java/aar.go"))
	for _, s := range []string{`"_testing1"`, `"_testing2"`, `"_testing3"`} {
		if !strings.Contains(string(aar), s) {
			t.Errorf("staged aar.go missing %s (chain not accumulating)", s)
		}
	}
	fin, _ := os.ReadFile(filepath.Join(root, stageDir, "build/soong/ui/build/finder.go"))
	for _, s := range []string{"func isTesting1Lane", "func isTesting2Lane", "func isTesting3Lane"} {
		if !strings.Contains(string(fin), s) {
			t.Errorf("staged finder.go missing %s", s)
		}
	}
	// testing1's own other-lane func must drop testing2 + testing3.
	seg := string(fin)
	i := strings.Index(seg, "func isOtherLaneBpForTesting1")
	if i < 0 {
		t.Fatal("isOtherLaneBpForTesting1 not generated")
	}
	body := seg[i:]
	if e := strings.Index(body, "\n}\n"); e > 0 {
		body = body[:e]
	}
	for _, s := range []string{`"-testing2"`, `"-testing3"`} {
		if !strings.Contains(body, s) {
			t.Errorf("isOtherLaneBpForTesting1 does not blind %s", s)
		}
	}
}

// TestApplyNothingStaged: apply with no staging dir is a clean no-op.
func TestApplyNothingStaged(t *testing.T) {
	if rc := applyStaged(t.TempDir()); rc != 0 {
		t.Errorf("apply with nothing staged should return 0, got %d", rc)
	}
}
