// Copyright 2026 The Android Open Source Project
// Copyright 2026 Sovereign Lane Surgeon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// bundlemanifest regenerates EVERY manifest the bundle needs, from the on-disk assets tree:
//
//	assets/aosp15_device.sha256    <sha256> <size> <path>   — content of every regular file
//	assets/aosp15_device.exec      <path>                   — files carrying an executable bit
//	assets/aosp15_device.symlinks  <path>\t<target>         — symbolic links
//	assets/aosp15_device.dirs      <path>                   — directories that hold no files
//
// WHY ONE COMMAND: `go:embed` is a LOSSY container. It carries regular-file CONTENT and nothing
// else — no mode bits, no symlinks, no empty directories. Each loss was found the same expensive
// way: a build failing far from the cause (executable bit, tangorpro 2026-09-02; symlink, husky
// 2026-09-03, 46 minutes in). They were also fixed one at a time, each with its own generator,
// so a NEW kind of loss had nothing regenerating it. This command emits all four together, from
// one walk, under one `go generate`, so no class can be silently left behind; `bundle audit`
// then proves the set is complete against a real source tree.
//
// Run from the repository root: go generate ./... (or go run ./cmd/bundlemanifest).
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const assetsRoot = "assets/aosp15_device"

type manifest struct {
	path, header string
	lines        []string
}

func (m *manifest) write() error {
	sort.Strings(m.lines)
	body := m.header
	if len(m.lines) > 0 {
		body += strings.Join(m.lines, "\n") + "\n"
	}
	return os.WriteFile(m.path, []byte(body), 0o644)
}

func main() {
	root := assetsRoot
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	content := &manifest{path: root + ".sha256",
		header: "# generated by cmd/bundlemanifest — sha256, size and path of every file in " + root + "; do not edit\n"}
	exec := &manifest{path: root + ".exec",
		header: "# generated by cmd/bundlemanifest — files carrying an executable bit in " + root + "; do not edit.\n" +
			"# embed.FS stats every file 0444; materializeEmbedded writes these 0755 (kati runs some of them via $(shell)).\n"}
	links := &manifest{path: root + ".symlinks",
		header: "# generated by cmd/bundlemanifest — <link path>\\t<link target> for every symlink in " + root + "; do not edit.\n" +
			"# go:embed drops symlinks entirely; materializeEmbedded recreates them from this list.\n"}
	dirs := &manifest{path: root + ".dirs",
		header: "# generated by cmd/bundlemanifest — directories in " + root + " that contain no files at any depth; do not edit.\n" +
			"# go:embed carries files only, so a directory that exists to be empty would vanish; materializeEmbedded recreates these.\n"}

	var totalBytes int64
	nonEmpty := map[string]bool{}
	var allDirs []string

	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, e error) error {
		if e != nil {
			return e
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return rerr
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil
		}
		switch {
		case d.IsDir():
			allDirs = append(allDirs, rel)
			return nil
		case d.Type()&fs.ModeSymlink != 0:
			target, lerr := os.Readlink(p)
			if lerr != nil {
				return lerr
			}
			links.lines = append(links.lines, rel+"\t"+filepath.ToSlash(target))
			markAncestors(nonEmpty, rel)
			return nil
		case !d.Type().IsRegular():
			// A fifo, socket or device node cannot travel in the bundle at all. None has ever
			// appeared in an AOSP source tree; refuse rather than drop it silently.
			return fmt.Errorf("%s is not a regular file, symlink or directory (%s) — the bundle cannot carry it", rel, d.Type())
		}
		fi, serr := d.Info()
		if serr != nil {
			return serr
		}
		f, oerr := os.Open(p)
		if oerr != nil {
			return oerr
		}
		h := sha256.New()
		n, cerr := io.Copy(h, f)
		f.Close()
		if cerr != nil {
			return cerr
		}
		totalBytes += n
		content.lines = append(content.lines, fmt.Sprintf("%s %d %s", hex.EncodeToString(h.Sum(nil)), n, rel))
		if fi.Mode()&0o111 != 0 {
			exec.lines = append(exec.lines, rel)
		}
		markAncestors(nonEmpty, rel)
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "bundlemanifest:", err)
		os.Exit(1)
	}
	for _, d := range allDirs {
		if !nonEmpty[d] {
			dirs.lines = append(dirs.lines, d)
		}
	}
	// Sort the content manifest by PATH, not by the hash the line starts with.
	sort.Slice(content.lines, func(i, j int) bool {
		return contentPath(content.lines[i]) < contentPath(content.lines[j])
	})
	content.lines = append([]string{}, content.lines...) // keep write() from re-sorting
	body := content.header + strings.Join(content.lines, "\n") + "\n"
	if err := os.WriteFile(content.path, []byte(body), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "bundlemanifest:", err)
		os.Exit(1)
	}
	for _, m := range []*manifest{exec, links, dirs} {
		if err := m.write(); err != nil {
			fmt.Fprintln(os.Stderr, "bundlemanifest:", err)
			os.Exit(1)
		}
	}
	fmt.Printf("%s: %d files, %d MB\n", content.path, len(content.lines), totalBytes/1e6)
	fmt.Printf("%s: %d executable files\n", exec.path, len(exec.lines))
	fmt.Printf("%s: %d symlinks\n", links.path, len(links.lines))
	fmt.Printf("%s: %d empty directories\n", dirs.path, len(dirs.lines))
}

// markAncestors records every directory on the path to rel as holding something.
func markAncestors(set map[string]bool, rel string) {
	for d := filepath.ToSlash(filepath.Dir(rel)); d != "." && d != "/"; d = filepath.ToSlash(filepath.Dir(d)) {
		set[d] = true
	}
}

// contentPath is the path field of a "<sha256> <size> <path>" line.
func contentPath(line string) string {
	f := strings.SplitN(line, " ", 3)
	if len(f) != 3 {
		return line
	}
	return f[2]
}
