// Copyright 2026 The Android Open Source Project
// Copyright 2026 Sovereign Lane Surgeon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// bundlemanifest regenerates assets/aosp15_device.sha256: one line per regular file under
// assets/aosp15_device — "<sha256> <size> <path>", sorted by path. The manifest is what the
// binary always embeds; the bundle CONTENT may be embedded (default build) or supplied at run
// time (-tags nobundle: -bundle-dir / -bundle-url, verified against this manifest, see
// bundle.go). Run from the repository root: go generate ./... (or go run ./cmd/bundlemanifest).
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	assetsRoot   = "assets/aosp15_device"
	manifestPath = "assets/aosp15_device.sha256"
)

func main() {
	root := assetsRoot
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	type row struct{ path, line string }
	var rows []row
	var total int64
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, e error) error {
		if e != nil {
			return e
		}
		if d.IsDir() {
			return nil
		}
		fi, serr := d.Info()
		if serr != nil || !fi.Mode().IsRegular() {
			return serr
		}
		f, oerr := os.Open(p)
		if oerr != nil {
			return oerr
		}
		h := sha256.New()
		n, cerr := io.Copy(h, f)
		f.Close()
		if cerr != nil {
			return cerr
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return rerr
		}
		total += n
		rows = append(rows, row{filepath.ToSlash(rel), fmt.Sprintf("%s %d %s", hex.EncodeToString(h.Sum(nil)), n, filepath.ToSlash(rel))})
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "bundlemanifest:", err)
		os.Exit(1)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].path < rows[j].path })
	lines := make([]string, 0, len(rows))
	for _, r := range rows {
		lines = append(lines, r.line)
	}
	out := "# generated by cmd/bundlemanifest — sha256, size and path of every file in " + root + "; do not edit\n" +
		strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(manifestPath, []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "bundlemanifest:", err)
		os.Exit(1)
	}
	fmt.Printf("%s: %d files, %d MB\n", manifestPath, len(lines), total/1e6)
}
