// Copyright 2026 The Android Open Source Project
// Copyright 2026 Sovereign Lane Surgeon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// symlinkmanifest regenerates assets/aosp15_device.symlinks: every symbolic link under
// assets/aosp15_device, as "<link path>\t<link target>", sorted by link path.
//
// WHY: go:embed carries regular file CONTENT only. It drops executable bits (see
// cmd/execmanifest) and it drops symlinks ENTIRELY — embed.FS has no way to represent one, and
// the walk simply does not yield them. AOSP's device/hardware trees use symlinks as
// compatibility headers: hardware/google/graphics/zuma/include/displaycolor/displaycolor_gs101.h
// -> ../gs101/displaycolor/displaycolor_gs101.h is how zuma's own
// include/zuma/displaycolor/displaycolor_zuma.h resolves `#include <displaycolor/…>` against the
// module's `include_dirs: ["hardware/google/graphics/zuma/include"]`. Without the link the
// revived tree compiles until something reaches libacryl and then fails with
// "fatal error: 'displaycolor/displaycolor_gs101.h' file not found" — observed 2026-09-03, the
// first zuma full build (husky, Build Capture run 083328Z), 46 minutes in.
//
// Run from the repository root: go generate ./... (or go run ./cmd/symlinkmanifest).
package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	assetsRoot   = "assets/aosp15_device"
	manifestPath = "assets/aosp15_device.symlinks"
)

func main() {
	root := assetsRoot
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	var lines []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, e error) error {
		if e != nil {
			return e
		}
		if d.Type()&fs.ModeSymlink == 0 {
			return nil
		}
		target, rerr := os.Readlink(p)
		if rerr != nil {
			return rerr
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return rerr
		}
		lines = append(lines, filepath.ToSlash(rel)+"\t"+filepath.ToSlash(target))
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "symlinkmanifest:", err)
		os.Exit(1)
	}
	sort.Strings(lines)
	out := "# generated by cmd/symlinkmanifest — <link path>\\t<link target> for every symlink in " + root + "; do not edit.\n" +
		"# go:embed drops symlinks entirely; materializeEmbedded recreates them from this list.\n" +
		strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(manifestPath, []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "symlinkmanifest:", err)
		os.Exit(1)
	}
	fmt.Printf("%s: %d symlinks\n", manifestPath, len(lines))
}
