// Copyright 2026 The Android Open Source Project
// Copyright 2026 Sovereign Lane Surgeon
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// execmanifest regenerates assets/aosp15_device.exec: the sorted list of every regular file
// under assets/aosp15_device that carries an executable bit on disk. Go's embed.FS keeps
// contents only (every embedded file stats as 0444), so without this manifest the bundle
// materializes AOSP's scripts as 0644 and kati's $(shell dir/script.sh) fails with
// "Permission denied" (observed: device/google/tangorpro/uwb/country_conf_gen.sh, 2026-09-02).
// Run from the repository root: go generate ./... (or go run ./cmd/execmanifest).
package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	assetsRoot   = "assets/aosp15_device"
	manifestPath = "assets/aosp15_device.exec"
)

func main() {
	root := assetsRoot
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	var paths []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, e error) error {
		if e != nil {
			return e
		}
		if d.IsDir() {
			return nil
		}
		fi, serr := d.Info()
		if serr != nil {
			return serr
		}
		if fi.Mode().IsRegular() && fi.Mode()&0o111 != 0 {
			rel, rerr := filepath.Rel(root, p)
			if rerr != nil {
				return rerr
			}
			paths = append(paths, filepath.ToSlash(rel))
		}
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "execmanifest:", err)
		os.Exit(1)
	}
	sort.Strings(paths)
	out := "# generated by cmd/execmanifest — executable files in " + root + "; do not edit\n" +
		strings.Join(paths, "\n") + "\n"
	if err := os.WriteFile(manifestPath, []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "execmanifest:", err)
		os.Exit(1)
	}
	fmt.Printf("%s: %d executable files\n", manifestPath, len(paths))
}
